# Generated by Django 6.0.6 on 2026-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_appuser_role_alter_customer_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texture',
            name='image_url',
        ),
        migrations.AddField(
            model_name='texture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='textures/'),
        ),
    ]
