# Generated by Django 6.0.6 on 2026-07-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_storage_locations', to='inventory.appuser'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_storage_locations', to='inventory.appuser'),
        ),
    ]
