# Generated by Django 6.0.6 on 2026-07-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_storagelocation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage_location',
            field=models.ForeignKey(blank=True, db_column='storage_location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.storagelocation'),
        ),
    ]
