# Generated by Django 6.0.6 on 2026-07-18 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_texture_created_at_texture_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_types', to='inventory.appuser'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_types', to='inventory.appuser'),
        ),
    ]
