# Generated by Django 6.0.6 on 2026-07-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_discount_created_at_discount_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['percent', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['percent', 'name']},
        ),
        migrations.AddField(
            model_name='tax',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_taxes', to='inventory.appuser'),
        ),
        migrations.AddField(
            model_name='tax',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_taxes', to='inventory.appuser'),
        ),
    ]
